#!/bin/bash

folder="$(readlink -f "$(dirname $0)")"
arduino_version=1.8.19
arduino_archive=arduino-${arduino_version}-linux64.tar.xz
arduino_url=https://downloads.arduino.cc/${arduino_archive}
arduino_folder=${folder}/arduino-${arduino_version}
arduino_link=${folder}/arduino-ide
arduino_portable=${arduino_link}/portable

# download & unpack arduino if required
if [[ ! -e ${arduino_folder} ]]; then
    echo "download ${arduino_url}"
    rm -rf ${arduino_archive} 2>/dev/null
    wget -q ${arduino_url}

    echo "unpack ${arduino_archive}"
    tar -xf ${arduino_archive}
    rm ${arduino_archive}

    echo "linking ${arduino_folder} -> ${arduino_link}"
    ln -s ${arduino_folder} ${arduino_link} 
fi

if [[ ! -d ${arduino_portable} ]]; then
    mkdir ${arduino_portable}
    ln -s ${folder}/sketchbook ${arduino_portable}/sketchbook
fi

./arduino-ide/arduino &
